# Generated by Django 4.1.3 on 2022-12-20 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'available'), ('not available', 'not available')], default='available', max_length=20)),
            ],
            options={
                'unique_together': {('day', 'start_time', 'end_time', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turff.ground')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='BookingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turff.pitch')),
                ('timeslot', models.ManyToManyField(to='Turff.timeslot')),
            ],
            options={
                'unique_together': {('startdate', 'enddate', 'pitch')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('taken', 'taken')], default='available', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('bookingdate_id', models.ManyToManyField(to='Turff.bookingdates')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Started', 'Started'), ('Completed', 'Completed')], default='Scheduled', max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turff.bookingdates')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turff.league')),
                ('teams', models.ManyToManyField(to='Turff.teams')),
            ],
            options={
                'unique_together': {('match_name', 'dates')},
            },
        ),
    ]
