# Generated by Django 4.1.3 on 2023-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turff', '0002_remove_match_teams_match_away_goals_match_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='total_matches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
